In [7]:
import implicit
import pandas as pd
import scipy

In [4]:
df = pd.read_csv('item_item_final.csv',index_col=0)
df.head(30)

      userId  movieId  rating   timestamp
66         4       66     0.5  1145937915
90         4      181     0.5  1127946789
93         4      193     0.5  1113766123
159        4      546     0.5  1115782390
296        4     1760     0.5  1114050751
341        4     2152     0.5  1115781964
363        4     2381     0.5  1135543160
371        4     2450     0.5  1113796599
417        4     2816     2.5  1123989912
466        4     3268     0.5  1114050659
484        4     3593     1.0  1115782046
524        4     3997     2.0  1113766387
757        4    42721     0.5  1145938348
1631      19      181     2.0   836433987
1657      19      286     3.0   849710700
1693      19      393     3.0   849710707
1739      19      546     3.0   849620598
1749      19      591     3.0   849710721
1773      19      737     3.0   836845026
1813      19     1170     3.0   849710721
1895      23      193     1.0  1193667802
1943      26      546     3.0  1225232084
2191      33      737     1.0  1187074082
2636      38     3973     2.0   979581741
2654      38     4124     3.0   982853654
2655      38     4125     1.0   982853654
2681      39      393     2.0  1077333349
2704      39     1556     2.0  1077333437
2709      39     1681     2.0  1077333328
2711      39     1707     3.0  1077333478

Options:

- ALS
- Bayesian Personalized Ranking
- Logistic Matrix Factorization
- NMSLib
- Annoy
- Faiss

In [8]:
sparse = scipy.sparse.csr_matrix(df.values)

In [10]:
als_model = implicit.als.AlternatingLeastSquares()

In [11]:
als_model.fit(sparse)

100%|██████████| 15.0/15 [00:41<00:00,  2.80s/it]

In [12]:
sim_items = als_model.similar_items(66)

In [13]:
sim_items

[(72135, nan),
 (72133, nan),
 (72136, nan),
 (72139, nan),
 (72134, nan),
 (72129, nan),
 (72132, nan),
 (72131, nan),
 (72130, nan),
 (216398, nan)]